using System;

namespace VisualStudio.Data
{
    public class Column
    {
        public string Name { get; set; }
        public SqlTypes SqlType { get; set; }
        public Type ClrType { get { return SqlType.ToClrType(); } }
        public int Length { get; set; }
        public string DefaultValue { get; set; }
        public bool IsNullable { get; set; }
        public bool IsIdentity { get; set; }
        public bool IsAutoGenerated { get; set; }
        public bool IsPrimaryKey { get; set; }
    }
}
